[[initial]]
== Install MongoDB 

You can find a installation guide for windows at https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/

For this guide to work, you must stand up a local MongoDB server for Windows(mongodb-win32-x86_64-2012plus-4.2.6-signed.msi).

You can find more installation options at https://docs.mongodb.org/manual/installation/.

After installing MongoDB and let the defult options, it will start as Windows Service.

== Test the Application

Install curl or postman tools.

Run spring application from your download local repository(local application folder) machine :

Ex.: 

c:\> ./mvnw spring-boot:run
build the JAR file 

c:\> ./mvnw clean package 
java -jar target/<your jar file name>.jar


Now that the application is running, you can test it. You can use any REST client you wish. 

First you want to see the top level service, as the following example shows:

====
[source,bash]
----
$ curl http://localhost:8080
{
  "_links" : {
    "planeta" : {
      "href" : "http://localhost:8080/planeta{?page,size,sort}",
      "templated" : true
    }
  }
}
----
====

The preceding example provides a first glimpse of what this server has to offer. There is
a `planeta` link located at http://localhost:8080/planeta. It has some options, such as
`?page`, `?size`, and `?sort`.

NOTE: Spring Data REST uses the http://stateless.co/hal_specification.html[HAL format] for
JSON output. It is flexible and offers a convenient way to supply links adjacent to the
data that is served.

When you use the planeta link, you see the `Planeta` records in the database (none at
present):

====
[source,bash]
----
c:\> curl http://localhost:8080/planeta
{
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/planeta{?page,size,sort}",
      "templated" : true
    },
    "search" : {
      "href" : "http://localhost:8080/planeta/search"
    }
  },
  "page" : {
    "size" : 20,
    "totalElements" : 0,
    "totalPages" : 0,
    "number" : 0
  }
}
----
====

There are currently no elements and, hence, no pages. It is time to create a new `Planeta`!

NOTE: If you run this guide multiple times, there may be leftover data. Refer to the
https://docs.mongodb.org/manual/reference/mongo-shell/[MongoDB shell quick reference] for
commands to find and drop your database if you need a fresh start.

The following command creats a person named "`PitzzaPlanet`":

====
[source,bash]
----
c:\> curl -i -X POST -H "Content-Type:application/json" -d "{  \"name\" : \"PitzzaPlanet\",  \"climate\" : \"desconhecido\" , \"terrain\" : \"desconhecido\"}" http://localhost:8080/planeta
HTTP/1.1 201 Created
Server: Apache-Coyote/1.1
Location: http://localhost:8080/planeta/53149b8e3004990b1af9f229
Content-Length: 0
Date: Mon, 03 Mar 2014 15:08:46 GMT
----

- `-i`: Ensures you can see the response message including the headers. The URI of the
newly created `Person` is shown.
- `-X POST`: Signals this a `POST` used to create a new entry.
- `-H "Content-Type:application/json"`: Sets the content type so the application knows the
payload contains a JSON object.
- `-d '{  "name" : "PitzzaPlanet",  "climate" : "desconhecido" , "terrain" : "desconhecido"}`: Is the data being sent.
====

NOTE: Notice how the previous `POST` operation includes a `Location` header. This contains
the URI of the newly created resource. Spring Data REST also has two methods
(`RepositoryRestConfiguration.setReturnBodyOnCreate(…)` and `setReturnBodyOnUpdate(…)`)
that you can use to configure the framework to immediately return the representation of
the resource just created/updated.

From this you can query for all planeta, as the following example shows:

====
[source,bash]
----
$ curl http://localhost:8080/planeta
{
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/planeta{?page,size,sort}",
      "templated" : true
    },
    "search" : {
      "href" : "http://localhost:8080/planeta/search"
    }
  },
  "_embedded" : {
    "planetas" : [ {
      "name" : "PitzzaPlanet", 
      "climate" : "quente" , 
      "terrain" : "desconhecido",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/planeta/53149b8e3004990b1af9f229"
        }
      }
    } ]
  },
  "page" : {
    "size" : 20,
    "totalElements" : 1,
    "totalPages" : 1,
    "number" : 0
  }
}
----
====

The `planetas` object contains a list with planeta. Notice how it includes a `self` link.
Spring Data REST also uses the
https://www.atteo.org/2011/12/12/Evo-Inflector.html[Evo Inflector] to pluralize the names
of entities for groupings.

You can directly query for the individual record, as the following example shows:

====
[source,bash]
----
c:\> curl http://localhost:8080/planeta/53149b8e3004990b1af9f229
{
 "name" : "PitzzaPlanet", 
 "climate" : "quente" , 
 "terrain" : "desconhecido",
 "_links" : {
    "self" : {
      "href" : "http://localhost:8080/planeta/53149b8e3004990b1af9f229"
    }
  }
}
----
====

NOTE: This might appear to be purely web-based, but, behind the scenes, it is talking to
the MongoDB database you started.

In this guide, there is only one domain object. With a more complex system, where domain
objects are related to each other, Spring Data REST renders additional links to help
navigate to connected records.

Find all the custom queries, as the following example shows:

====
[source,bash]
----
$ curl http://localhost:8080/planeta/search
{
  "_links" : {
    "findByName" : {
      "href" : "http://localhost:8080/planeta/search/findByName{?name}",
      "templated" : true
    }
  }
}
----
====

You can see the URL for the query, including the HTTP query parameter, `name`. This
matches the `@Param("name")` annotation embedded in the interface.

To use the `findByName` query, run the following  command:

====
[source,bash]
----
c:\> curl http://localhost:8080/planeta/search/findByName?name=PitzzaPlanet
{
  "_embedded" : {
      "planetas" : [ {
      "name" : "PitzzaPlanet",  
      "climate" : "quente", 
      "terrain" : "desconhecido",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/planeta/53149b8e3004990b1af9f229"
        }
      }
    } ]
  }
}
----
====

====
[source,bash]
----
c:\> curl http://localhost:8080/planeta/search/findById?_id=53149b8e3004990b1af9f229
{
  "_embedded" : {
      "planetas" : [ {
      "name" : "PitzzaPlanet",  
      "climate" : "quente", 
      "terrain" : "desconhecido",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/planeta/53149b8e3004990b1af9f229"
        }
      }
    } ]
  }
}
----
====

Because you defined it to return `List<Person>` in the code, it returns all of the
results. If you had defined it to return only `Person`, it picks one of the `Person`
objects to return. Since this can be unpredictable, you probably do not want to do that
for queries that can return multiple entries.

You can also issue `PUT`, `PATCH`, and `DELETE` REST calls to replace, update, or delete
existing records, respectively. The following example uses a `PUT` call:

====
[source,bash]
----
$ curl -X PUT -H "Content-Type:application/json" -d "{  \"name\" : \"PitzzaPlanet-Atualizado\",  \"climate\" : \"quente\" , \"terrain\" : \"desconhecido\"}" http://localhost:8080/planeta/53149b8e3004990b1af9f229
$ curl http://localhost:8080/planeta/53149b8e3004990b1af9f229
{
  "name" : "PitzzaPlanet",  
  "climate" : "quente", 
  "terrain" : "desconhecido",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/planeta/53149b8e3004990b1af9f229"
    }
  }
}
----
====

The following example uses a `PATCH` call:

====
[source,bash]
----
$ curl -X PATCH -H "Content-Type:application/json" -d "{ \"name\": \"BetaPlanet\" }" http://localhost:8080/planeta/53149b8e3004990b1af9f229
$ curl http://localhost:8080/planeta/53149b8e3004990b1af9f229
{
  "name" : "BetaPlanet",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/planeta/53149b8e3004990b1af9f229"
    }
  }
}
----
====

NOTE: `PUT` replaces an entire record. Fields not supplied will be replaced with `null`.
You can use `PATCH` to update a subset of items.

You can also delete records, as the following example shows:

====
[source,bash]
----
$ curl -X DELETE http://localhost:8080/planeta/53149b8e3004990b1af9f229
$ curl http://localhost:8080/planeta
{
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/planeta{?page,size,sort}",
      "templated" : true
    },
    "search" : {
      "href" : "http://localhost:8080/planeta/search"
    }
  },
  "page" : {
    "size" : 20,
    "totalElements" : 0,
    "totalPages" : 0,
    "number" : 0
  }
}
----
====

